### ISSUE TITLE
Literatur zu Edge, Cloud und Fog Computing

### ISSUE THREAD

**Issue by bajkad** [dxiai/multimico-cluster#6]
**Zum Einstieg**
- https://zhaw.swisscovery.slsp.ch/permalink/41SLSP_ZAW/47r7nv/cdi_hrcak_primary_oai_hrcak_srce_hr_125740

**Vertiefung**
- https://zhaw.swisscovery.slsp.ch/permalink/41SLSP_ZAW/1ivdr18/alma99116709299805510
- https://zhaw.swisscovery.slsp.ch/permalink/41SLSP_ZAW/1ivdr18/alma99116709646605510
- https://zhaw.swisscovery.slsp.ch/permalink/41SLSP_ZAW/1ivdr18/alma99116710879505510

**Theorien und Konzepte**
- https://www.wiley.com/en-us/Fog+and+Edge+Computing%3A+Principles+and+Paradigms-p-9781119525066
- https://www.wiley.com/en-us/Fog%2C+Edge%2C+and+Pervasive+Computing+in+Intelligent+IoT+Driven+Applications-p-9781119670100
- https://www.wiley.com/en-us/Fog+Computing%3A+Theory+and+Practice-p-9781119551775

**Konferenz-Proceedings**
- https://zhaw.swisscovery.slsp.ch/permalink/41SLSP_ZAW/1ivdr18/alma99116726098805510

**Comment by phish108** [comment]
Dieses Issue hat nicht wirklich etwas mit dem Cluster zu tun.

**Comment by phish108** [comment]
@bajkad wichtiger überblick https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8100873

**Comment by phish108** [comment]
Dieses Issue wurde in das Hauptrepo umgezogen dxiai/multimico#1
