### ISSUE TITLE
Dieses Issue hat nicht wirklich etwas mit dem Cluster zu tun.

### ISSUE THREAD

**Issue by bajkad** [dxiai/multimico-cluster#8]
Wohin würdest du es dann auf Github tun? 

Dieses Issue hat nicht wirklich etwas mit dem Cluster zu tun. 

__Originally posted by @phish108 in https://github.com/dxiai/multimico-cluster/issues/6#issuecomment-777356117__

**Comment by phish108** [comment]
Prinzip ist folgendes: 

Das `multimico-cluster` Repo betrifft  **nur** das cluster und wie wir das aufsetzen und erweitern. Das betrifft die Hardware Hosts und die VMs. Da wir hier keinen Code haben, enthält  das Repo die Cloud-Init-Dateien und die Ansible Playbooks für die Installation und Wartung der Hardware und VMs.

Für MultiMICO  machen wir ein eigenes Repo mit  dem Namen `multimico`.  In dieses Repo gehen alle theoretischen und konzeptionellen Information. Literatur-Verweise gehören in dieses Repo.

Für die Container erstellen wir jeweils ein separates Repo für den Code des Containers. Die Minimalversion enthält also immer ein `Dockerfile`.

Für die Installation der Container in den jeweiligen Clustern gibt es ein eigenes Repo für die Konfiguration der Container im MultiMICO Cluster. Diese Repos fangen alle mit `multimico-` an.

Andere Projekte wie "machen können" erhalten ein eigenes Repo. Wenn wir besondere Inhalte und Komponenten für diese Projekte entwickeln, dann  bekommen auch die ein eigenes Repo mit dem jeweiligen projektnamen als prefix.
